wechat.mp.client:
  - name: zhuangqf
    router:
      - default
    config:
      appid: wx757dad7ff56abe8a
      secret: ebbc2d79f426e654647296e01fcdca8e
      token: loveDaiDai
#      aesKey: "testAesKey"

wechat.mp.rules:
  "default":
    end: true
    handlers:
      - com.zhuangqf.wechat.demo.handler.DefaultHandler

